### ISSUE TITLE
where's the source code about crawler?

### ISSUE THREAD

**Issue by sonyfe25cp** [soulmachine/domain-crawler#1]
Hi fangqin,
1. where's the source code about whois ?
2. In my memory, someday you created a repo about how to crawl proxy from kinds of website, but I can't find it now. That's a good example for beginners to learn web crawler.

I try to learn how to write a crawler with scala. 
:)

Jie Chen

**Comment by soulmachine** [comment]
https://github.com/crowdcrawler/ProxyCrawler

**Comment by sonyfe25cp** [comment]
Thanks!
